### ISSUE TITLE
Many services that shouldn't be accessible via Instance.new()

### ISSUE THREAD

**Issue by CoolDoctorWho** [Anaminus/roblox-bug-tracker#544] opened 2015-01-04 21:49 UTC
![screenshot_2](https://cloud.githubusercontent.com/assets/4654283/5607640/08cc69a0-945b-11e4-8734-3fd07e8ec53c.png)

To replicate :

game:GetService("InsertService"):LoadAsset(AnyGame).Parent=Somewhere

It is also possible to steal places which have loadstring enabled via this and uploading the data to a pastebin as raw XML then opening in studio.

**Comment by matthewdean** [comment] 2015-01-05 01:01
Duplicate of #474

**Closed by matthewdean** 2015-01-05 01:01 UTC
