### ISSUE TITLE
Multiple variable declarations in one line do not show up in autocomplete

### ISSUE THREAD

**Issue by TheIcyStar** [Anaminus/roblox-bug-tracker#800] opened 2016-08-19 00:44 UTC
When editing a script in studio, you can usually see autocomplete suggestions whenever you start typing variables or typing out paths like game.Workspace. (and so on).

However, if multiple variables are defined in one line, they do not show up in autocomplete.
`local Var1, Var2, Var3 = "Foo", "Bar", 76`

Var1 would show up in autocomplete, Var2 and Var3 would not.

**Comment by matthewdean** [comment] 2016-10-22 21:56
Duplicate of https://github.com/Anaminus/roblox-bug-tracker/issues/769

**Closed by matthewdean** 2016-10-22 21:56 UTC
Labels: bug, duplicate, Studio
