### ISSUE TITLE
CFrame constructor accepts arbitrary userdata in arguments

### ISSUE THREAD

**Issue by CoffeeFlux** [Anaminus/roblox-bug-tracker#720] opened 2015-09-17 01:35 UTC
The following lines of code will both generate a CFrame that includes nan for at least one of the components, and when run cause issues with both dynamic lighting and the camera (all white screen):

```
game:GetService('Workspace').Part.CFrame = CFrame.new(newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true), newproxy(true))
```
```
game:GetService('Workspace').Part.CFrame = CFrame.new(newproxy(true), newproxy(true), 0, 0,0,0,0)
```

It appears that the constructor is not checking to ensure the values passed are of the correct type (might just be checking to make sure it's userdata?)

Something similar appears to have previously reported in issue #659. 
Thanks to cntkillme for the idea.

**Comment by SNCPlay42** [comment] 2015-09-17 07:26
Probably related to/the same thing as #593

**Comment by CoffeeFlux** [comment] 2015-09-18 01:22
Yeah, it appears to be the same thing. While it may be intended behavior, this really should be changed. It's particularly annoying because the other CFrame constructors (`CFrame.new(newproxy(true))`, for example) will error with `bad argument`.

**Comment by Anaminus** [comment] 2015-11-06 13:21
Essentially a duplicate of #593.

**Closed** 2015-11-06 13:35 UTC
Labels: bug, duplicate, Engine
