### ISSUE TITLE
Intellisense backspacing causing studio crashes.

### ISSUE THREAD

**Issue by VesuviusSentinel** [Anaminus/roblox-bug-tracker#775] opened 2016-04-05 22:57 UTC
It would seem so far that studio is only crashing in this form when you backspace or delete the first letter of a word while intellisense is suggesting something. 
Steps to replicate:

1. Start typing something like "and" or "break" or "BrickColor" but do not type it all the way out.
2. Start deleting the letters, when you get to the first letter and try to delete it studio crashes.

I did try to replicate this multiple times, and it happened every time with the only exception being if I had already completed typing the word. I tried it in a new script, in a new place as well with the same results.

**Comment by The0neThe0nly** [comment] 2016-04-07 19:09
I am unable to reproduce this issue.

**Comment by VesuviusSentinel** [comment] 2016-04-07 22:25
Is it possible it is a platform based studio glitch? I'm running this on the Mac version, if that's of any concern at all.

**Comment by The0neThe0nly** [comment] 2016-04-09 02:27
In that case, it probably is mac-specific. It would be much appreciated if somebody else running OS X could verify the issue.

**Comment by OnlyTwentyCharacters** [comment] 2016-05-16 03:07
No longer crashes.

**Comment by The0neThe0nly** [comment] 2016-05-22 04:16
@VesuviusSentinel, please close this issue.

**Closed** 2016-05-22 07:46 UTC
