### ISSUE TITLE
ROBLOX Error When Updating Group Rolesets

### ISSUE THREAD

**Issue by HaywardMaster191** [Anaminus/roblox-bug-tracker#580] opened 2015-03-22 01:08 UTC
When you try to Update ROBLOX group Role Sets it will take you to the ROBLOX error Page and will only UPLOAD half the roleset names and keep the rest the same name,

**Comment by matthewdean** [comment] 2015-03-22 02:04
Possible duplicate of #418

**Closed** 2015-03-27 22:24 UTC
Labels: bug, needsinfo, Website
