### ISSUE TITLE
Audio Loudness Angle Dependent [bug] [engine]

### ISSUE THREAD

**Issue by Vectricity** [Anaminus/roblox-bug-tracker#696] opened 2015-08-16 03:17 UTC
At the following place "http://www.roblox.com/games/35377716/USA-Washington-D-C-Pre-Alpha?nl=true#" you will come across an odd issue where audio (specifically from the "Sound" object) is loud at some angles, but quiet at other angles. I believe this to be a bug that only appears at places with a high part count as I've not encountered this issue at other places. Sounds that happen at one end of the map can be heard at the other side of the map if facing your camera one way, but cannot be heard when facing your camera another way. This is a most unusual issue.

Additional details: Just discovered that the issue emerges when a certain distance from position 0,0,0. At the map I mentioned, the Capitol Building is nearest 0,0,0. I was riding a motorcycle that has an engine sound and when about half way from the White House to the Capitol Building, the audio issue disappeared. Heading back towards the White House caused the issue to reappear.

**Comment by Vectricity** [comment] 2015-08-16 04:21
Just checked to be sure and it happens in Studio as well as in the player. Sorry for switching the label back and forth.

**Comment by Anaminus** [comment] 2015-08-29 01:37
Duplicate of #26.

**Closed by Anaminus** 2015-08-29 01:37 UTC
